version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    open-pull-requests-limit: 10
    groups:
      eslint:
        patterns:
          - '*eslint*'
    ignore:
      - dependency-name: '*eslint*'
        update-types:
          - 'version-update:semver-major'
